# Data Wrangling Practice Using Pandas


## Learning Objectives

By completing this notebook, students will learn how to:

- Load CSV files using Pandas
- Explore datasets
- Handle missing values
- Rename columns
- Filter rows
- Convert data types
- Create new columns
- Sort and group data
- Perform aggregation
- Export cleaned data

In [1]:

import pandas as pd

## Create Sample Dataset

In [7]:

data = {
    "OrderID": [1001,1002,1003,1004,1005,1006,1007,1008,1008,1009,1010],
    "Customer": ["Ali","Sara","John","Aisha","Mike","Emily","Ali","Sara","Sara","John","Aisha"],
    "Category": ["Electronics","Electronics","Furniture","Electronics","Furniture","Clothing","electronics","Clothing","Clothing","Furniture","Clothing"],
    "Product": ["Laptop","Phone","Chair",None,"Table","Jacket","Tablet","Shoes","Shoes","Sofa","T-Shirt"],
    "Price": [1200,800,150,900,None,200,450,120,120,950,35],
    "Quantity": [1,2,4,1,1,2,1,3,3,1,5],
    "OrderDate": ["2025-01-12","2025-01-15","2025-01-16","2025-01-18","2025-01-20","2025-01-21","2025-01-22","2025-01-25","2025-01-25","2025-01-28","2025-01-29"],
    "City": ["Toronto","Montreal","Vancouver","Toronto","Calgary",None,"Toronto","Montreal","Montreal","Vancouver","Toronto"]
}

df = pd.DataFrame(data)

df.to_csv("sales_data.csv", index=False)

print("Dataset created successfully.")
print(df.head())

Dataset created successfully.
   OrderID Customer     Category Product   Price  Quantity   OrderDate  \
0     1001      Ali  Electronics  Laptop  1200.0         1  2025-01-12
1     1002     Sara  Electronics   Phone   800.0         2  2025-01-15
2     1003     John    Furniture   Chair   150.0         4  2025-01-16
3     1004    Aisha  Electronics     NaN   900.0         1  2025-01-18
4     1005     Mike    Furniture   Table     NaN         1  2025-01-20

        City
0    Toronto
1   Montreal
2  Vancouver
3    Toronto
4    Calgary

## Load the Dataset

In [1]:

df = pd.read_csv("sales_data.csv")

df.head()

NameError: name 'pd' is not defined

## Explore Dataset Information

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    11 non-null     int64
 1   Customer   11 non-null     str
 2   Category   11 non-null     str
 3   Product    10 non-null     str
 4   Price      10 non-null     float64
 5   Quantity   11 non-null     int64
 6   OrderDate  11 non-null     str
 7   City       10 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 836.0 bytes

In [9]:
df.describe()

           OrderID        Price   Quantity
count    11.000000    10.000000  11.000000
mean   1005.727273   492.500000   2.181818
std       2.969542   429.723748   1.401298
min    1001.000000    35.000000   1.000000
25%    1003.500000   127.500000   1.000000
50%    1006.000000   325.000000   2.000000
75%    1008.000000   875.000000   3.000000
max    1010.000000  1200.000000   5.000000

## Check Missing Values

In [10]:
df.isnull().sum()

OrderID      0
Customer     0
Category     0
Product      1
Price        1
Quantity     0
OrderDate    0
City         1
dtype: int64

## Handle Missing Values

In [11]:

df["Product"] = df["Product"].fillna("Unknown")

average_price = df["Price"].mean()

df["Price"] = df["Price"].fillna(average_price)

df["City"] = df["City"].fillna("Unknown")

df

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal
2,1003,John,Furniture,Chair,150.0,4,2025-01-16,Vancouver
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto
4,1005,Mike,Furniture,Table,492.5,1,2025-01-20,Calgary
5,1006,Emily,Clothing,Jacket,200.0,2,2025-01-21,Unknown
6,1007,Ali,electronics,Tablet,450.0,1,2025-01-22,Toronto
7,1008,Sara,Clothing,Shoes,120.0,3,2025-01-25,Montreal
8,1008,Sara,Clothing,Shoes,120.0,3,2025-01-25,Montreal
9,1009,John,Furniture,Sofa,950.0,1,2025-01-28,Vancouver
10,1010,Aisha,Clothing,T-Shirt,35.0,5,2025-01-29,Toronto

## Detect and Remove Duplicates

In [12]:

print("Duplicate Rows:")
print(df.duplicated())

df = df.drop_duplicates()

print("\nDataset Shape After Removing Duplicates:")
print(df.shape)

Duplicate Rows:
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
dtype: bool

Dataset Shape After Removing Duplicates:
(10, 8)

## Standardize Text Values

In [13]:

df["Category"] = df["Category"].str.capitalize()

df["Category"].unique()

<StringArray>
['Electronics', 'Furniture', 'Clothing']
Length: 3, dtype: str

## Create New Column

In [14]:

df["TotalSales"] = df["Price"] * df["Quantity"]

df.head()

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal,1600.0
2,1003,John,Furniture,Chair,150.0,4,2025-01-16,Vancouver,600.0
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto,900.0
4,1005,Mike,Furniture,Table,492.5,1,2025-01-20,Calgary,492.5

## Convert Data Types

In [15]:

df["OrderDate"] = pd.to_datetime(df["OrderDate"])

df.dtypes

OrderID                int64
Customer                 str
Category                 str
Product                  str
Price                float64
Quantity               int64
OrderDate     datetime64[us]
City                     str
TotalSales           float64
dtype: object

## Filter Data

In [16]:

electronics_df = df[df["Category"] == "Electronics"]

electronics_df

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal,1600.0
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto,900.0
6,1007,Ali,Electronics,Tablet,450.0,1,2025-01-22,Toronto,450.0

In [17]:

high_sales = df[df["Price"] > 500]

high_sales

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal,1600.0
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto,900.0
9,1009,John,Furniture,Sofa,950.0,1,2025-01-28,Vancouver,950.0

## Sort Data

In [18]:

sorted_df = df.sort_values(by="TotalSales", ascending=False)

sorted_df

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal,1600.0
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
9,1009,John,Furniture,Sofa,950.0,1,2025-01-28,Vancouver,950.0
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto,900.0
2,1003,John,Furniture,Chair,150.0,4,2025-01-16,Vancouver,600.0
4,1005,Mike,Furniture,Table,492.5,1,2025-01-20,Calgary,492.5
6,1007,Ali,Electronics,Tablet,450.0,1,2025-01-22,Toronto,450.0
5,1006,Emily,Clothing,Jacket,200.0,2,2025-01-21,Unknown,400.0
7,1008,Sara,Clothing,Shoes,120.0,3,2025-01-25,Montreal,360.0
10,1010,Aisha,Clothing,T-Shirt,35.0,5,2025-01-29,Toronto,175.0

## Grouping and Aggregation

In [19]:

category_sales = df.groupby("Category")["TotalSales"].sum()

category_sales

Category
Clothing        935.0
Electronics    4150.0
Furniture      2042.5
Name: TotalSales, dtype: float64

In [20]:

average_category_price = df.groupby("Category")["Price"].mean()

average_category_price

Category
Clothing       118.333333
Electronics    837.500000
Furniture      530.833333
Name: Price, dtype: float64

## Export Cleaned Dataset

In [21]:

df.to_csv("cleaned_sales_data.csv", index=False)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

## Mini Challenges

In [22]:

# Challenge 1
# Find all orders from Toronto

toronto_orders = df[df["City"] == "Toronto"]

toronto_orders

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
3,1004,Aisha,Electronics,Unknown,900.0,1,2025-01-18,Toronto,900.0
6,1007,Ali,Electronics,Tablet,450.0,1,2025-01-22,Toronto,450.0
10,1010,Aisha,Clothing,T-Shirt,35.0,5,2025-01-29,Toronto,175.0

In [23]:

# Challenge 2
# Find top 3 highest sales

top_sales = df.sort_values(by="TotalSales", ascending=False).head(3)

top_sales

,OrderID,Customer,Category,Product,Price,Quantity,OrderDate,City,TotalSales
1,1002,Sara,Electronics,Phone,800.0,2,2025-01-15,Montreal,1600.0
0,1001,Ali,Electronics,Laptop,1200.0,1,2025-01-12,Toronto,1200.0
9,1009,John,Furniture,Sofa,950.0,1,2025-01-28,Vancouver,950.0

In [24]:

# Challenge 3
# Count number of orders per city

city_orders = df["City"].value_counts()

city_orders

City
Toronto      4
Montreal     2
Vancouver    2
Calgary      1
Unknown      1
Name: count, dtype: int64

In [25]:

# Challenge 4
# Find total revenue generated

total_revenue = df["TotalSales"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 7127.5